spring.application.name=microservicio-usuarios
#puerto random
server.port=${PORT:0}
#server.port=8088
eureka.instance.instance-id=${spring.application.name}:${random.value}

#configuracion de ruta donde esta Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

######################        conexion MariaDB    ##################################
#spring.datasource.url=jdbc:mysql://localhost:3306/db_microservicios_examenes
#spring.datasource.username=root
#spring.datasource.password=qwerty
#conexion Pstgres
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
####################################################################################
######################        conexion Postgres    ##################################
spring.datasource.url=jdbc:postgresql://localhost:5432/db_microservicios_usuarios
spring.datasource.username=postgres
spring.datasource.password=qwerty
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Crea las tablas automaticamente
spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug

#configurar warning
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true